// Constants and Initial Data for NDS Traffic 2026

export const CENTERS = [
  { id: 'El Kattamia', nameAr: 'القطامية', nameEn: 'El Kattamia', city: 'Cairo', cityAr: 'القاهرة' },
  { id: 'Hadayek El Ahram', nameAr: 'حدائق الأهرام', nameEn: 'Hadayek El Ahram', city: 'Cairo', cityAr: 'القاهرة' },
  { id: 'Smoha', nameAr: 'سموحة', nameEn: 'Smoha', city: 'Alexandria', cityAr: 'الإسكندرية' },
  { id: 'Merghem', nameAr: 'مرغم', nameEn: 'Merghem', city: 'Alexandria', cityAr: 'الإسكندرية' },
  { id: 'Antoniados', nameAr: 'انطونيادس', nameEn: 'Antoniados', city: 'Alexandria', cityAr: 'الإسكندرية' },
  { id: 'Maryland', nameAr: 'ميريلاند', nameEn: 'Maryland', city: 'Cairo', cityAr: 'القاهرة' },
];

export const COMPANIES = [
  'N Auto Express',
  'NDS For Car Service',
  'NDS For Distribution'
];

export const BRANDS = [
  'Jetour',
  'Skoda',
  'SEAT',
  'Rox',
  'ROX MOTOR',
  'NISSAN',
  'HYUNDAI',
  'PROTON',
  'VENUCIA',
  'PEUGEOT',
  'FORD',
  'KIA PICANTO',
  'VOLVO',
  'SUZUKI',
  'CHEVROLET',
  'MITSUBISHI'
];

export const INITIAL_BOOKINGS = [
  // --- 04-Aug-2026 ---
  {
    id: 'b-04aug-1',
    date: '2026-08-04',
    company: 'N Auto Express',
    center: 'Hadayek El Ahram',
    city: 'Cairo',
    serviceType: 'Mechanical',
    brand: 'Jetour',
    bookingsCount: 2,
    actualMechanical: 5,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
    weCare: 1,
    guarantee: 1,
  },
  {
    id: 'b-04aug-2',
    date: '2026-08-04',
    company: 'N Auto Express',
    center: 'Smoha',
    city: 'Alexandria',
    serviceType: 'Mechanical',
    brand: 'HYUNDAI',
    bookingsCount: 1,
    actualMechanical: 2,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
    weCare: 1,
  },
  {
    id: 'b-04aug-3',
    date: '2026-08-04',
    company: 'N Auto Express',
    center: 'Merghem',
    city: 'Alexandria',
    serviceType: 'Mechanical',
    brand: 'Skoda',
    bookingsCount: 0,
    actualMechanical: 0,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
  },

  // NDS For Car Service
  {
    id: 'b-04aug-4',
    date: '2026-08-04',
    company: 'NDS For Car Service',
    center: 'Hadayek El Ahram',
    city: 'Cairo',
    serviceType: 'Mechanical',
    brand: 'Skoda',
    bookingsCount: 2,
    actualMechanical: 11,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
    guarantee: 1,
  },
  {
    id: 'b-04aug-5',
    date: '2026-08-04',
    company: 'NDS For Car Service',
    center: 'Smoha',
    city: 'Alexandria',
    serviceType: 'Mechanical',
    brand: 'Skoda',
    bookingsCount: 4,
    actualMechanical: 13,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
    weCare: 1,
    guarantee: 2,
    bodyAndPaint: 1,
  },
  {
    id: 'b-04aug-6',
    date: '2026-08-04',
    company: 'NDS For Car Service',
    center: 'Antoniados',
    city: 'Alexandria',
    serviceType: 'Mechanical',
    brand: 'SEAT',
    bookingsCount: 0,
    actualMechanical: 0,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
  },

  // NDS For Distribution
  {
    id: 'b-04aug-7',
    date: '2026-08-04',
    company: 'NDS For Distribution',
    center: 'El Kattamia',
    city: 'Cairo',
    serviceType: 'Mechanical',
    brand: 'Rox',
    bookingsCount: 7,
    actualMechanical: 11,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
    bodyAndPaint: 2,
    goodwill: 1,
  },
  {
    id: 'b-04aug-8',
    date: '2026-08-04',
    company: 'NDS For Distribution',
    center: 'Merghem',
    city: 'Alexandria',
    serviceType: 'Mechanical',
    brand: 'PROTON',
    bookingsCount: 0,
    actualMechanical: 0,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
    goodwill: 1,
  },

  // --- 30-Jul-2026 ---
  {
    id: 'b-30jul-1',
    date: '2026-07-30',
    company: 'NDS For Distribution',
    center: 'El Kattamia',
    city: 'Cairo',
    serviceType: 'Mechanical',
    brand: 'Jetour',
    bookingsCount: 5,
    actualMechanical: 9,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
  },
  {
    id: 'b-30jul-2',
    date: '2026-07-30',
    company: 'NDS For Car Service',
    center: 'Merghem',
    city: 'Alexandria',
    serviceType: 'Mechanical',
    brand: 'Skoda',
    bookingsCount: 3,
    actualMechanical: 7,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
  },

  // --- 29-Jul-2026 ---
  {
    id: 'b-29jul-1',
    date: '2026-07-29',
    company: 'NDS For Distribution',
    center: 'El Kattamia',
    city: 'Cairo',
    serviceType: 'Mechanical',
    brand: 'Jetour',
    bookingsCount: 7,
    actualMechanical: 6,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
  },

  // --- 01-Aug-2026 ---
  {
    id: 'b-01aug-1',
    date: '2026-08-01',
    company: 'NDS For Distribution',
    center: 'El Kattamia',
    city: 'Cairo',
    serviceType: 'Mechanical',
    brand: 'Jetour',
    bookingsCount: 5,
    actualMechanical: 6,
    actualCarCare: 0,
    actualBoth: 0,
    cancelled: 0,
  },
];
